# -*- coding: utf-8 -*-
"""preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsE8N40274wcMADYxatRRv83i1urd4tc
"""

import pandas as pd


def load_data(filepath):
    """Load dataset."""
    return pd.read_csv(filepath)


def convert_date(df, column="Date"):
    """Convert date column to datetime."""
    df[column] = pd.to_datetime(df[column])
    return df


def check_missing_values(df):
    """Return missing values count."""
    return df.isnull().sum()


def interpolate_missing_values(df, columns):
    """Interpolate missing numerical values."""
    df[columns] = df[columns].interpolate(method="linear")
    return df


def remove_remaining_missing(df):
    """Drop remaining missing values."""
    return df.dropna()


def remove_duplicates(df):
    """Remove duplicate rows."""
    return df.drop_duplicates()

def save_clean_data(df, filepath):
    """Save cleaned dataset to a CSV file."""
    df.to_csv(filepath, index=False)

# Load dataset
df = load_data("/content/city_day.csv")

# Convert Date column
df = convert_date(df)

# Check missing values
print(check_missing_values(df))

# Columns to interpolate
columns = [
    "PM2.5",
    "PM10",
    "NO",
    "NO2",
    "NOx",
    "NH3",
    "CO",
    "SO2",
    "O3",
    "Benzene",
    "Toluene",
    "Xylene",
    "AQI"
]

# Data preprocessing
df = interpolate_missing_values(df, columns)
df = remove_duplicates(df)
df = remove_remaining_missing(df)

# Save cleaned dataset
save_clean_data(df, "data/processed/cleaned_aqi.csv")

# Display first five rows
print(df.head())